apiVersion: v1
kind: Namespace
metadata:
  name: my-app-dev
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: my-app-dev
  labels:
    app: devops
spec:
  ports:
    - port: 3306
  selector:
    app: devops
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: my-app-dev
  labels:
    app: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devops-mysql
  namespace: my-app-dev
  labels:
    app: devops
spec:
  selector:
    matchLabels:
      app: devops
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devops
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: configmap
  namespace: my-app-dev
data:
  dbhost: "10.96.0.5"
  dbname: "devops_dev"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  namespace: my-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
        - name: gke-test
          image: gondragon/my_app:dev
          env:
          - name: PORT
            value: "3000"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: dbuser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: dbpassword
          - name: DB_NAME
            valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: dbname
          - name: DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: dbhost
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: my-app-dev
type: Opaque
data:
  dbuser: cm9vdA==
  dbpassword: MTIzNA==
---
apiVersion: v1
kind: Service
metadata:
  name: gke-test-service
  namespace: my-app-dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: gke-test
    